const ActionTypes = {
     FETCH_CHATS_SUCCESS: "FETCH_CHATS_SUCCESS",
     GROUP_CREATED_SUCCESSFULLY: "GROUP_CREATED_SUCCESSFULLY",
     HANDLE_MODAL:"HANDLE_MODAL",
     GROUPS_FETCHED_SUCCESS:"GROUPS_FETCHED_SUCCESS",
     GET_SPECIFIC_GROUP_SUCCESS:"GET_SPECIFIC_GROUP_SUCCESS",
     JOIN_GROUP_REQUESTS_SUCCESS:"JOIN_GROUP_REQUESTS_SUCCESS",
     FETCH_MEMBERS_SUCCESS:"FETCH_MEMBERS_SUCCESS",
     FETCH_ADMINS_SUCCESS:"FETCH_ADMINS_SUCCESS"
 }
 
 export default ActionTypes;